// Copyright 2026 hugo-bluecorn
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// GENERATED BY tool/gen/generate_rules.dart — DO NOT EDIT.
// Source: IESDP @ 8adef1c
//
// These are the game's own rules tables, transcribed by a program rather than
// by hand. Regenerate rather than editing:
//   fvm dart run tool/gen/generate_rules.dart

/// Dexterity to armour class. Confirmed against the game, which printed
/// "Dexterity: -3" for a score of 17. Generated from
/// `files/2da/2da_bgee/dexmod.2da`.
const Map<int, int> dexterityArmourClass = {
  0: 5,
  1: 5,
  2: 4,
  3: 3,
  4: 2,
  5: 1,
  6: 0,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: -1,
  16: -2,
  17: -3,
  18: -4,
  19: -4,
  20: -4,
  21: -5,
  22: -5,
  23: -5,
  24: -6,
  25: -6,
};

/// Constitution to hit points per level, for everyone but warriors. Confirmed
/// at 16, where the game printed "Bonus Hit Points/Level: +2". Generated from
/// `files/2da/2da_bgee/hpconbon.2da, column OTHER`.
const Map<int, int> constitutionHitPointsOther = {
  1: -3,
  2: -2,
  3: -2,
  4: -1,
  5: -1,
  6: -1,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 1,
  16: 2,
  17: 2,
  18: 2,
  19: 2,
  20: 2,
  21: 2,
  22: 2,
  23: 2,
  24: 2,
  25: 2,
};

/// The same, for fighters, paladins and rangers. The two columns are identical
/// up to 16 and diverge from 17, so the fixture cannot tell them apart.
/// Generated from `files/2da/2da_bgee/hpconbon.2da, column WARRIOR`.
const Map<int, int> constitutionHitPointsWarrior = {
  1: -3,
  2: -2,
  3: -2,
  4: -1,
  5: -1,
  6: -1,
  7: 0,
  8: 0,
  9: 0,
  10: 0,
  11: 0,
  12: 0,
  13: 0,
  14: 0,
  15: 1,
  16: 2,
  17: 3,
  18: 4,
  19: 5,
  20: 5,
  21: 6,
  22: 6,
  23: 6,
  24: 7,
  25: 7,
};
